// <auto-generated />
using System;
using Catalog.Infra.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Catalog.Infra.Migrations
{
    [DbContext(typeof(CatalogContext))]
    [Migration("20251107143622_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Catalog.Domain.Entities.ProductEntity", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateInclusion")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ProductActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ProductDepth")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProductHeight")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductWeight")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProductWidth")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Sku")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("be056cb4-fb6f-40a6-81ec-4b896072dee6"),
                            DateInclusion = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 1m,
                            ProductActive = false,
                            ProductDepth = 1m,
                            ProductDescription = "That feeling of hope you've missed during you long walk until this moment in your life",
                            ProductHeight = 1m,
                            ProductName = "Lost Hope",
                            ProductWeight = "1ton",
                            ProductWidth = 1m,
                            Sku = 1m
                        },
                        new
                        {
                            ProductId = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba96"),
                            DateInclusion = new DateTime(2025, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 1m,
                            ProductActive = false,
                            ProductDepth = 1m,
                            ProductDescription = "That feeling once experienced but you can't find it anywhere at all",
                            ProductHeight = 1m,
                            ProductName = "Good Feeling",
                            ProductWeight = "1ton",
                            ProductWidth = 1m,
                            Sku = 1m
                        },
                        new
                        {
                            ProductId = new Guid("2902b665-1190-4c70-9915-b9c2d7680450"),
                            DateInclusion = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 1m,
                            ProductActive = false,
                            ProductDepth = 1m,
                            ProductDescription = "The first night that you've spent awake without any special reason and you regret it doing so",
                            ProductHeight = 1m,
                            ProductName = "Night Sleep",
                            ProductWeight = "1ton",
                            ProductWidth = 1m,
                            Sku = 1m
                        },
                        new
                        {
                            ProductId = new Guid("102b566b-ba1f-404c-b2df-e2cde39ade09"),
                            DateInclusion = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 1m,
                            ProductActive = false,
                            ProductDepth = 1m,
                            ProductDescription = "Happiness when you laugh about some silly thing",
                            ProductHeight = 1m,
                            ProductName = "Smile",
                            ProductWeight = "1ton",
                            ProductWidth = 1m,
                            Sku = 1m
                        },
                        new
                        {
                            ProductId = new Guid("5b3621c0-7b12-4e80-9c8b-3398cba7ee05"),
                            DateInclusion = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 1m,
                            ProductActive = false,
                            ProductDepth = 1m,
                            ProductDescription = "Baffled moments of life when you don't know what to say",
                            ProductHeight = 1m,
                            ProductName = "Baffled moment",
                            ProductWeight = "1ton",
                            ProductWidth = 1m,
                            Sku = 1m
                        },
                        new
                        {
                            ProductId = new Guid("2aadd2df-7caf-45ab-9355-7f6332985a87"),
                            DateInclusion = new DateTime(2025, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 1m,
                            ProductActive = false,
                            ProductDepth = 1m,
                            ProductDescription = "A small piece of childhood when there weren't any worried",
                            ProductHeight = 1m,
                            ProductName = "Childhood",
                            ProductWeight = "1ton",
                            ProductWidth = 1m,
                            Sku = 1m
                        },
                        new
                        {
                            ProductId = new Guid("2ee49fe3-edf2-4f91-8409-3eb25ce6ca51"),
                            DateInclusion = new DateTime(2025, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 1m,
                            ProductActive = false,
                            ProductDepth = 1m,
                            ProductDescription = "Magic artifact that grant many power to its carrier",
                            ProductHeight = 1m,
                            ProductName = "Unicorn Horn",
                            ProductWeight = "1ton",
                            ProductWidth = 1m,
                            Sku = 1m
                        },
                        new
                        {
                            ProductId = new Guid("5b1c2b4d-48c7-402a-80c3-cc796ad49c6b"),
                            DateInclusion = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 1m,
                            ProductActive = false,
                            ProductDepth = 1m,
                            ProductDescription = "A good memory that has been lost",
                            ProductHeight = 1m,
                            ProductName = "Memories",
                            ProductWeight = "1ton",
                            ProductWidth = 1m,
                            Sku = 1m
                        },
                        new
                        {
                            ProductId = new Guid("d8663e5e-7494-4f81-8739-6e0de1bea7ee"),
                            DateInclusion = new DateTime(2025, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 1m,
                            ProductActive = false,
                            ProductDepth = 1m,
                            ProductDescription = "Rain drops during a sleepy night at a cozy home",
                            ProductHeight = 1m,
                            ProductName = "Rain Drops",
                            ProductWeight = "1ton",
                            ProductWidth = 1m,
                            Sku = 1m
                        },
                        new
                        {
                            ProductId = new Guid("34489196-0766-48bb-9918-f36e6ac81da8"),
                            DateInclusion = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 1m,
                            ProductActive = false,
                            ProductDepth = 1m,
                            ProductDescription = "That feeling of hope you've missed during you long walk until this moment in your life",
                            ProductHeight = 1m,
                            ProductName = "Lost Hope 2",
                            ProductWeight = "1ton",
                            ProductWidth = 1m,
                            Sku = 1m
                        },
                        new
                        {
                            ProductId = new Guid("73e1b95e-2754-40de-947e-c1cb4f1e7f67"),
                            DateInclusion = new DateTime(2025, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 1m,
                            ProductActive = false,
                            ProductDepth = 1m,
                            ProductDescription = "That feeling once experienced but you can't find it anywhere at all",
                            ProductHeight = 1m,
                            ProductName = "Good Feeling 2",
                            ProductWeight = "1ton",
                            ProductWidth = 1m,
                            Sku = 1m
                        },
                        new
                        {
                            ProductId = new Guid("42ed050d-37ec-4c1f-9bff-84990ac3adda"),
                            DateInclusion = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 1m,
                            ProductActive = false,
                            ProductDepth = 1m,
                            ProductDescription = "The first night that you've spent awake without any special reason and you regret it doing so",
                            ProductHeight = 1m,
                            ProductName = "Night Sleep 2",
                            ProductWeight = "1ton",
                            ProductWidth = 1m,
                            Sku = 1m
                        },
                        new
                        {
                            ProductId = new Guid("498f0ef6-e542-434b-8277-992f770e9118"),
                            DateInclusion = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 1m,
                            ProductActive = false,
                            ProductDepth = 1m,
                            ProductDescription = "Happiness when you laugh about some silly thing",
                            ProductHeight = 1m,
                            ProductName = "Smile 2",
                            ProductWeight = "1ton",
                            ProductWidth = 1m,
                            Sku = 1m
                        },
                        new
                        {
                            ProductId = new Guid("164a2e03-bd51-4e0f-9e53-b7c181b00104"),
                            DateInclusion = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 1m,
                            ProductActive = false,
                            ProductDepth = 1m,
                            ProductDescription = "Baffled moments of life when you don't know what to say",
                            ProductHeight = 1m,
                            ProductName = "Baffled moment 2",
                            ProductWeight = "1ton",
                            ProductWidth = 1m,
                            Sku = 1m
                        },
                        new
                        {
                            ProductId = new Guid("ef9a2698-a31e-416e-ac92-f2ca02b5a9d3"),
                            DateInclusion = new DateTime(2025, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 1m,
                            ProductActive = false,
                            ProductDepth = 1m,
                            ProductDescription = "A small piece of childhood when there weren't any worried",
                            ProductHeight = 1m,
                            ProductName = "Childhood 2",
                            ProductWeight = "1ton",
                            ProductWidth = 1m,
                            Sku = 1m
                        },
                        new
                        {
                            ProductId = new Guid("e96bcc8a-4696-4cd9-a86c-32c8421146f7"),
                            DateInclusion = new DateTime(2025, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 1m,
                            ProductActive = false,
                            ProductDepth = 1m,
                            ProductDescription = "Magic artifact that grant many power to its carrier",
                            ProductHeight = 1m,
                            ProductName = "Unicorn Horn 2",
                            ProductWeight = "1ton",
                            ProductWidth = 1m,
                            Sku = 1m
                        },
                        new
                        {
                            ProductId = new Guid("ee215607-f2c7-4e48-8df6-3442d00bdbc7"),
                            DateInclusion = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 1m,
                            ProductActive = false,
                            ProductDepth = 1m,
                            ProductDescription = "A good memory that has been lost",
                            ProductHeight = 1m,
                            ProductName = "Memories 2",
                            ProductWeight = "1ton",
                            ProductWidth = 1m,
                            Sku = 1m
                        },
                        new
                        {
                            ProductId = new Guid("c8705360-1fc4-4a1a-8380-77c7a2d18b6e"),
                            DateInclusion = new DateTime(2025, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 1m,
                            ProductActive = false,
                            ProductDepth = 1m,
                            ProductDescription = "Rain drops during a sleepy night at a cozy home",
                            ProductHeight = 1m,
                            ProductName = "Rain Drops 2",
                            ProductWeight = "1ton",
                            ProductWidth = 1m,
                            Sku = 1m
                        },
                        new
                        {
                            ProductId = new Guid("375f3d27-caec-4416-a4e6-6d9e5685815e"),
                            DateInclusion = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 1m,
                            ProductActive = false,
                            ProductDepth = 1m,
                            ProductDescription = "That feeling of hope you've missed during you long walk until this moment in your life",
                            ProductHeight = 1m,
                            ProductName = "Lost Hope 3",
                            ProductWeight = "1ton",
                            ProductWidth = 1m,
                            Sku = 1m
                        },
                        new
                        {
                            ProductId = new Guid("20c1bfd6-1241-4a33-befd-d6392e23f5d6"),
                            DateInclusion = new DateTime(2025, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 1m,
                            ProductActive = false,
                            ProductDepth = 1m,
                            ProductDescription = "That feeling once experienced but you can't find it anywhere at all",
                            ProductHeight = 1m,
                            ProductName = "Good Feeling 3",
                            ProductWeight = "1ton",
                            ProductWidth = 1m,
                            Sku = 1m
                        },
                        new
                        {
                            ProductId = new Guid("e6af373b-c907-4c48-968e-3879a234892b"),
                            DateInclusion = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 1m,
                            ProductActive = false,
                            ProductDepth = 1m,
                            ProductDescription = "The first night that you've spent awake without any special reason and you regret it doing so",
                            ProductHeight = 1m,
                            ProductName = "Night Sleep 3",
                            ProductWeight = "1ton",
                            ProductWidth = 1m,
                            Sku = 1m
                        },
                        new
                        {
                            ProductId = new Guid("7e3f11f6-3493-4799-8d24-fc5c7ea31f6a"),
                            DateInclusion = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 1m,
                            ProductActive = false,
                            ProductDepth = 1m,
                            ProductDescription = "Happiness when you laugh about some silly thing",
                            ProductHeight = 1m,
                            ProductName = "Smile 3",
                            ProductWeight = "1ton",
                            ProductWidth = 1m,
                            Sku = 1m
                        },
                        new
                        {
                            ProductId = new Guid("dae0cedb-e1bd-40ee-a6cd-c32732446114"),
                            DateInclusion = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 1m,
                            ProductActive = false,
                            ProductDepth = 1m,
                            ProductDescription = "Baffled moments of life when you don't know what to say",
                            ProductHeight = 1m,
                            ProductName = "Baffled moment 3",
                            ProductWeight = "1ton",
                            ProductWidth = 1m,
                            Sku = 1m
                        },
                        new
                        {
                            ProductId = new Guid("94635dc2-0cc8-4ab5-b8c0-dd01ab4d30f4"),
                            DateInclusion = new DateTime(2025, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 1m,
                            ProductActive = false,
                            ProductDepth = 1m,
                            ProductDescription = "A small piece of childhood when there weren't any worried",
                            ProductHeight = 1m,
                            ProductName = "Childhood 3",
                            ProductWeight = "1ton",
                            ProductWidth = 1m,
                            Sku = 1m
                        },
                        new
                        {
                            ProductId = new Guid("f93923a5-3d34-4df0-be32-4237dda10d41"),
                            DateInclusion = new DateTime(2025, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 1m,
                            ProductActive = false,
                            ProductDepth = 1m,
                            ProductDescription = "Magic artifact that grant many power to its carrier",
                            ProductHeight = 1m,
                            ProductName = "Unicorn Horn 3",
                            ProductWeight = "1ton",
                            ProductWidth = 1m,
                            Sku = 1m
                        },
                        new
                        {
                            ProductId = new Guid("17f181fa-d2c7-4a1a-9848-163958e8b771"),
                            DateInclusion = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 1m,
                            ProductActive = false,
                            ProductDepth = 1m,
                            ProductDescription = "A good memory that has been lost",
                            ProductHeight = 1m,
                            ProductName = "Memories 3",
                            ProductWeight = "1ton",
                            ProductWidth = 1m,
                            Sku = 1m
                        },
                        new
                        {
                            ProductId = new Guid("e3b711c8-9e11-4b6d-bdd9-1cf4eb40bade"),
                            DateInclusion = new DateTime(2025, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 1m,
                            ProductActive = false,
                            ProductDepth = 1m,
                            ProductDescription = "Rain drops during a sleepy night at a cozy home",
                            ProductHeight = 1m,
                            ProductName = "Rain Drops 3",
                            ProductWeight = "1ton",
                            ProductWidth = 1m,
                            Sku = 1m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
